version: "3.7"
services:
  main:
    container_name: main
    build:
      context: .
      target: production
    environment:
      NODE_ENV: production
    command: node dist/main
    ports:
      - 9000:3000
      - 9999:3001 # development port
