# each container should do one thing and do it well
version: "3.7"
services:
  worker:
    container_name: worker
    build:
      context: .
      target: production
    command: node dist/main
    volumes:
      - .:/usr/src/worker
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:5
